# docker-compose.yml

version: '3.3'

services:
  api:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0'
    volumes:
      - .:/app
    expose:
      - 8000
    environment:
      - DATABASE_URL=postgresql://fec_db:fec_db@db:5432/fec_db
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`ec2-35-81-83-141.us-west-2.compute.amazonaws.com`)"

  db:
    image: postgres:13-alpine
    volumes:
      - ./.postgres:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=fec_db
      - POSTGRES_PASSWORD=fec_db
      - POSTGRES_DB=fec_db

  traefik:
    image: traefik:v2.2
    ports:
      - 8008:80
      - 8081:8080
    volumes:
      - "./traefik.dev.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  postgres_data:
